//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public int BugID { get; set; }
        public string BugTitle { get; set; }
        public string BugDescription { get; set; }
        public System.DateTime BugOpened { get; set; }
        public string BugAssigned { get; set; }
        public Nullable<bool> BugClosed { get; set; }
    }
}
